ANIMALS = (
    {
        "id": "cow",
        "name": "Cow",
        "sound_label": "Moo",
        "image_path": "animals/cow.svg",
        "sound_pattern": "moo",
    },
    {
        "id": "horse",
        "name": "Horse",
        "sound_label": "Neigh",
        "image_path": "animals/horse.svg",
        "sound_pattern": "neigh",
    },
    {
        "id": "sheep",
        "name": "Sheep",
        "sound_label": "Baa",
        "image_path": "animals/sheep.svg",
        "sound_pattern": "baa",
    },
    {
        "id": "pig",
        "name": "Pig",
        "sound_label": "Oink",
        "image_path": "animals/pig.svg",
        "sound_pattern": "oink",
    },
    {
        "id": "chicken",
        "name": "Chicken",
        "sound_label": "Cluck",
        "image_path": "animals/chicken.svg",
        "sound_pattern": "cluck",
    },
    {
        "id": "duck",
        "name": "Duck",
        "sound_label": "Quack",
        "image_path": "animals/duck.svg",
        "sound_pattern": "quack",
    },
    {
        "id": "goat",
        "name": "Goat",
        "sound_label": "Bleat",
        "image_path": "animals/goat.svg",
        "sound_pattern": "bleat",
    },
    {
        "id": "donkey",
        "name": "Donkey",
        "sound_label": "Hee-haw",
        "image_path": "animals/donkey.svg",
        "sound_pattern": "hee-haw",
    },
    {
        "id": "dog",
        "name": "Dog",
        "sound_label": "Woof",
        "image_path": "animals/dog.svg",
        "sound_pattern": "bark",
    },
    {
        "id": "cat",
        "name": "Cat",
        "sound_label": "Meow",
        "image_path": "animals/cat.svg",
        "sound_pattern": "meow",
    },
    {
        "id": "lion",
        "name": "Lion",
        "sound_label": "Roar",
        "image_path": "animals/lion.svg",
        "sound_pattern": "roar",
    },
    {
        "id": "monkey",
        "name": "Monkey",
        "sound_label": "Chatter",
        "image_path": "animals/monkey.svg",
        "sound_pattern": "chatter",
    },
    {
        "id": "gorilla",
        "name": "Gorilla",
        "sound_label": "Grunt",
        "image_path": "animals/gorilla.svg",
        "sound_pattern": "gorilla-grunt",
    },
    {
        "id": "tiger",
        "name": "Tiger",
        "sound_label": "Growl",
        "image_path": "animals/tiger.svg",
        "sound_pattern": "tiger-growl",
    },
)
